# Generated by Django 2.0 on 2019-04-01 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battleships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='battleships.Game'),
            preserve_default=False,
        ),
    ]
