# Generated by Django 2.1.7 on 2019-03-24 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battleships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='modified',
            new_name='last_modified',
        ),
        migrations.AddField(
            model_name='game',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
